### PR TITLE
Updates and fix

### PR DESCRIPTION
**Pull request by MarkOdey**
- I provided a new rounding feature along the decimal so we don't get numbers that don't corresponds to the 'step' specified.
- I am making sure that position is relative to the actual knob not a relative position of a different element. (This was due to an interaction conflict if the cursor was registering an event from a different dom element)
Sorry I am new with github. So I may have been misusing issues and pull requests.

Thanks

Mark

### CODE REVIEW

**Comment by kramer99** [comment]
It's not clear to me at all what this is attempting to fix.

I see a lot of extra complexity with the potential to break use cases for the many existing users of this component.

There also appear to be other unrelated changes that should be in separate PRs.

**Comment by MarkOdey** [comment]
Yes I am sorry, my fork is slowly diverging since I am actively using this component on one of my project. I should have provided multiple hotfix branch instead.

>  Iam making sure that position is relative to the actual knob not a relative position of a different element. (This was due to an interaction conflict if the cursor was registering an event from a different dom element)

Do you understand what I mean by this? Basically every mousemove event was using the position relative to the target initally. 

` this.updatePosition(e.offsetX, e.offsetY);`

This is wrong, since this depends on the target element of you event.  Which may not be your knob element. That's why you get erratic numbers when moving you mouse outside :

 ` <svg :width="computedSize" :height="computedSize" viewBox="0 0 100 100"
            @click="onClick"
            @mousedown="onMouseDown"
            @mouseup="onMouseUp"
            @touchstart="onTouchStart"
            @touchend="onTouchEnd">`

What I am doing, I am using the clientX clientY position of the event. This provides the cursor position in the screen. Then I substract the position off the your knob element position.

`this.updatePosition(e.clientX, e.clientY);`

and in updatePosition

`const boundingClientRect = this.$el.getBoundingClientRect();
 //Calculating the positionning from client screen positioning. 
//This avoids concflict of dom offsetX position from the event target.
const dx = offsetX - (boundingClientRect.left+boundingClientRect.right)/2;
const dy =  (boundingClientRect.top+boundingClientRect.bottom)/2 - offsetY;`

As for the rounding. The pattern is actually simple. I am just rounding the values based on the decimal provided after the stepSize. If I want to do steps of 0.x there is no point of keeping the 0.0x. This was disrupting my layout and giving me unexpected numbers. 

So what I do is I cast my number into a string and split the string at the decimal point.

`let stepChunks = this.stepSize.toString().split('.');`

Then I store the decimalSize. If there are no decimal point, the second item will be undefined. Therefore I check if its undefined and give a decimalSize of 0.

`  let decimalSize = stepChunks[1] != undefined ?  stepChunks[1].length : 0;`

Then the magnitude is basically to compute the number maximum size to preserve. It putting the decimal size to base 10. Therefore 10^0=1 10^1=10 10^3=100 etc. If I multiply this magnitude with the value I am then offseting the number of digits to perserve. Finally I simply round this number then normalize it back to its original size. This will ensure that decimal numbers respects the stepsize.

I really appreciate your initiative @kramer99 and I would love to keep your project living and growing. 

As mentioned before consider me an newbie here so if you can guide me to make these amendments useful it would make my day otherwise its all fine. 

Good day 

Mark

**Comment by kramer99** [comment]
Can you provide an example of using the component that creates the problem you describe?  I'll go and test it out myself.

**Comment by kramer99** [comment]
Closing due to no followup after a year.

**Pull request closed without merging**
